src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Language</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SponsorProduct__c.object
<CustomObject>
    <fields>
        <fullName>Sponsor__c</fullName>
        <label>Sponsor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account selected must be a sponsor</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sponsors</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProductType</valueSetName>
        </valueSet>
    </fields>
    <label>Sponsor Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsors Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SponsorSiteList__c.object
<CustomObject>
    <description>Management of prefered Site Lists for Sponsors</description>
    <fields>
        <fullName>SponsorProduct__c</fullName>
        <label>Sponsor Product</label>
        <referenceTo>SponsorProduct__c</referenceTo>
        <relationshipLabel>Sponsor Site Lists</relationshipLabel>
        <relationshipName>SponsorSiteLists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sponsor Site List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsors Site Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SponsorSiteListJoinTable__c.object
<CustomObject>
    <description>Join table for the selection of prefered Account Site in the Account Sponsor Record Type</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <label>AccountID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SponsorSiteListID__c</fullName>
        <label>Sponsor Site List ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sponsor SiteList Join Table</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsor SiteList Join Table</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SponsorSiteListControllerTest.cls
@isTest
public class SponsorSiteListControllerTest
{

	@isTest
	public static void testgetSiteList(){

		Account accountSite = new Account(Name='Test', ShippingStreet='Gouvernment', RecordTypeId='012f4000000iYKbAAM', language__c='English');

		test.startTest();
			insert accountSite;
		test.stopTest();

		List<Account> insertedAcc =  SponsorSiteListController.getSiteList('5','1');
	}

	@isTest
	public static void testgetSiteSelected(){

		List<String> preferredSiteList = new List<String>();

		test.startTest();

			List<Account> AccountSiteList = new List<Account>();
			
			for(Integer i=0; i<10; i++) {
				Account acc 		= new Account();
				acc.Name    		= 'Site Account' + i; 
				acc.RecordTypeId    ='012f4000000iYKbAAM'  ;
				acc.language__c 	= 'English';
				AccountSiteList.add(acc);
			}
			insert AccountSiteList;

			Account childAccount = new Account(Name='Site Account A', ParentId=AccountSiteList[0].Id ,RecordTypeId='012f4000000iYKbAAM', language__c='English');
			insert childAccount;

			Account accountSponsor = new Account(Name='Account Sponsor test', RecordTypeId='012f4000000iYKWAA2', language__c='English');
			insert accountSponsor;
			
			SponsorProduct__c Product = new SponsorProduct__c(Name='Test', Type__c='OTC', Sponsor__c=accountSponsor.Id);
			insert Product;

			SponsorSiteList__c sponsorList = new SponsorSiteList__c(name='Test site List', SponsorProduct__c=Product.Id);
			insert sponsorList;

			List<SponsorSiteListJoinTable__c> SponsorJoinList = new List<SponsorSiteListJoinTable__c>();
			
			for(Account a : AccountSiteList){
				SponsorSiteListJoinTable__c joinObj = new SponsorSiteListJoinTable__c();
				joinObj.AccountID__c=a.Id;
				joinObj.SponsorSiteListID__c=sponsorList.Id;
			}
			insert SponsorJoinList;

			String recordId = sponsorList.Id;
			String pageSize = '5';

			preferredSiteList = SponsorSiteListController.getSiteSelected(pageSize, recordId);
				
		test.stopTest();
	}

	@isTest
	public static void testsaveSiteSelection(){

		List<String> selection = new List<String>();
		selection.add('sdfsdfsd');
		selection.add('sdfsdfsasdfd');

		String recordId = 'Gouvernment';

		SponsorSiteListController.saveSiteSelection(recordId, selection);

	}

	@isTest
	public static void testgetPostalCodeListFiltred()
	{
		String postalcode = 'sdfsafs \n dsfsfsd \n sfsdfsfs \n sdfsdf \n';

		SponsorSiteListController.getPostalCodeListFiltred (postalcode);

	}
}