src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Language</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Language</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ExclusionJoinTable__c.object
<CustomObject>
    <fields>
        <fullName>AccountID__c</fullName>
        <label>AccountID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactID__c</fullName>
        <label>ContactID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <label>ProductID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SponsorID__c</fullName>
        <label>SponsorID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exclusion Join Table</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exclusion Joins Table</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SponsorProduct__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>An inactive Product and his Site Lists won&apos;t be used in the distribution calculation</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <label>Sponsor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The account selected must be a sponsor</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sponsors</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProductType</valueSetName>
        </valueSet>
    </fields>
    <label>Sponsor Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsors Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SponsorSiteList__c.object
<CustomObject>
    <description>Management of prefered Site Lists for Sponsors</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SponsorProduct__c</fullName>
        <label>Sponsor Product</label>
        <referenceTo>SponsorProduct__c</referenceTo>
        <relationshipLabel>Sponsor Site Lists</relationshipLabel>
        <relationshipName>SponsorSiteLists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sponsor Site List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsors Site Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SponsorSiteListJoinTable__c.object
<CustomObject>
    <description>Join table for the selection of prefered Account Site in the Account Sponsor Record Type</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <label>AccountID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SponsorSiteListID__c</fullName>
        <label>Sponsor Site List ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sponsor SiteList Join Table</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsor SiteList Join Table</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TriggerTest.cls
@isTest
private class TriggerTest {
	
	@isTest static void AccountTrigger() {
			
		String ACCOUNT_SITE_RECORDTYPE = '012f4000000iYKbAAM';
		String ACCOUNT_SPONSOR_RECORDTYPE = '012f4000000iYKWAA2';

		Account sponsor = new Account(Name='Test', Industry='Gouvernment', Type='Competitor', language__c ='English', RecordTypeId=ACCOUNT_SPONSOR_RECORDTYPE);
		Account site = new Account(Name='Test', Industry='Gouvernment', Type='Competitor', language__c ='English', RecordTypeId=ACCOUNT_SITE_RECORDTYPE);

		test.startTest();
		insert sponsor;
		insert site;

		// Test Exclusion Table
		ExclusionJoinTable__c exclusion = new ExclusionJoinTable__c(AccountID__c = site.Id, SponsorID__c=sponsor.Id );
		insert exclusion;

		SponsorProduct__c Product = new SponsorProduct__c(Name='Test', Type__c='OTC', Sponsor__c=sponsor.Id);
		insert Product;

		// Create a sponsor Site List
		SponsorSiteList__c sponsorList = new SponsorSiteList__c(name='Test site List', SponsorProduct__c=Product.Id);
		insert sponsorList;

		SponsorSiteListJoinTable__c SponsorJoinList = new SponsorSiteListJoinTable__c(AccountID__c=site.Id, SponsorSiteListID__c=sponsorList.Id);
		insert SponsorJoinList;

		delete sponsor;
		delete site;
		test.stopTest();
	}

	@isTest static void SponsorSiteListTriggerActive() {

		String ACCOUNT_SITE_RECORDTYPE = '012f4000000iYKbAAM';
		String ACCOUNT_SPONSOR_RECORDTYPE = '012f4000000iYKWAA2';
		List<SponsorSiteList__c> SitesList = new List<SponsorSiteList__c>();


		test.startTest();
			
			Account Sponsor = new Account(Name='TestSponsor', Industry='Gouvernment', Type='Competitor', language__c ='English', RecordTypeId=ACCOUNT_SPONSOR_RECORDTYPE);

			insert Sponsor;

			SponsorProduct__c Product = new SponsorProduct__c(Name='Test', Type__c='OTC', Sponsor__c=Sponsor.Id);

			insert Product;

			SponsorSiteList__c spsl = new SponsorSiteList__c();
			spsl.Name = 'Name A';
			spsl.SponsorProduct__c = Product.Id;
			spsl.Active__c = true;

			insert spsl;

			SponsorSiteList__c spsl2 = new SponsorSiteList__c();
			spsl2.Name = 'Name B';
			spsl2.SponsorProduct__c = Product.Id;
			spsl2.Active__c = true;

			try {
           		insert spsl2;
			}
			catch(Exception e) {
				System.assert(e.getMessage().contains('You can\'t have 2 actives lists for a same Product. Please verify the following list :Name A'));
			}

		test.stopTest();
	}

	@isTest static void SponsorSiteListTriggerDelete() {

		String ACCOUNT_SITE_RECORDTYPE = '012f4000000iYKbAAM';
		String ACCOUNT_SPONSOR_RECORDTYPE = '012f4000000iYKWAA2';
		
		List<SponsorSiteList__c> SitesList = new List<SponsorSiteList__c>();
		
		test.startTest();
			Account Sponsor = new Account(Name='TestSponsor', Industry='Gouvernment', Type='Competitor', language__c ='English', RecordTypeId=ACCOUNT_SPONSOR_RECORDTYPE);
			insert Sponsor;
			
			SponsorProduct__c Product = new SponsorProduct__c(Name='Test', Type__c='OTC', Sponsor__c=Sponsor.Id);
			Account site = new Account(Name='Test', Industry='Gouvernment', Type='Competitor', language__c ='English', RecordTypeId=ACCOUNT_SITE_RECORDTYPE);
			insert site;
			insert Product;

			SponsorSiteList__c spsl = new SponsorSiteList__c();
			spsl.Name = 'Name A';
			spsl.SponsorProduct__c = Product.Id;
			spsl.Active__c = false;

			insert spsl;

			SponsorSiteListJoinTable__c SponsorJoinList = new SponsorSiteListJoinTable__c(AccountID__c=site.Id, SponsorSiteListID__c=spsl.Id);
			insert SponsorJoinList;

			delete spsl;

		test.stopTest();
	}

	@isTest static void SponsorProductTriggerDelete()
	{

		test.startTest();

			Account Account = new Account(Name='Test', Industry='Gouvernment', Type='Competitor', language__c ='English',RecordTypeId='012f4000000iYKWAA2');
			insert Account;

			SponsorProduct__c product = new SponsorProduct__c(Name = 'Test', Type__c='OTC', Sponsor__c=Account.Id);
			insert product;

			ExclusionJoinTable__c newExclusion = new ExclusionJoinTable__c(ProductID__c=product.ID, AccountID__c=Account.Id);
			insert newExclusion;

			delete product;
			
		test.stopTest();

	}


	@isTest static void ContactTriggerDelete()
	{

		test.startTest();

			Contact Contact = new Contact(LastName='Test', language__c ='English');
			insert Contact;
		
			ExclusionJoinTable__c newExclusion = new ExclusionJoinTable__c(ContactID__c=Contact.Id);
			insert newExclusion;

			delete Contact;
			
		test.stopTest();

	}
	
}